/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Instance": {                                    "en": "Instance",                                        "de": "Instanz",                                         "ru": "Инстанция",                                       "pt": "Instância",                                       "nl": "Instantie",                                       "fr": "Instance",                                        "it": "Esempio",                                         "es": "Instancia",                                       "pl": "Instancja",                                       "zh-cn": "例"},
    "extraAttr": {                                   "en": "extraAttr",                                       "de": "extraAttr",                                       "ru": "extraAttr",                                       "pt": "extraAttr",                                       "nl": "extraAttr",                                       "fr": "extraAttr",                                       "it": "extraAttr",                                       "es": "extraAttr",                                       "pl": "extraAttr",                                       "zh-cn": "extraAttr"},
    "group_extraMyset": {                            "en": "extraMyset",                                      "de": "extraMyset",                                      "ru": "extraMyset",                                      "pt": "extraMyset",                                      "nl": "extraMyset",                                      "fr": "extraMyset",                                      "it": "extraMyset",                                      "es": "extraMyset",                                      "pl": "extraMyset",                                      "zh-cn": "extraMyset"},
    "htmlText": {                                    "en": "htmlText",                                        "de": "htmlText",                                        "ru": "htmlText",                                        "pt": "htmlText",                                        "nl": "htmlText",                                        "fr": "htmlText",                                        "it": "htmlText",                                        "es": "htmlText",                                        "pl": "htmlText",                                        "zh-cn": "htmlText"},
    "myColor": {                                     "en": "myColor",                                         "de": "meineColor",                                      "ru": "Мой цвет",                                        "pt": "minhaCor",                                        "nl": "mijnKleur",                                       "fr": "maCouleur",                                       "it": "mioColore",                                       "es": "miColor",                                         "pl": "mójKolor",                                        "zh-cn": "我的颜色"},
    "myColor_tooltip": {                             "en": "Description of myColor",                          "de": "Beschreibung von myColor",                        "ru": "Описание myColor",                                "pt": "Descrição de myColor",                            "nl": "Beschrijving van myColor",                        "fr": "Description de myColor",                          "it": "Descrizione di myColor",                          "es": "Descripción de myColor",                          "pl": "Opis myColor",                                    "zh-cn": "myColor的描述"},
    "card-icon-open": {                              "en": "Open Icon",                                       "de": "Symbol öffnen",                                   "ru": "Открыть значок",                                  "pt": "Ícone aberto",                                    "nl": "Open Icoon",                                      "fr": "Icône ouverte",                                   "it": "Apri icona",                                      "es": "Abrir icono",                                     "pl": "Otwórz ikonę",                                    "zh-cn": "开启图示"},
};